# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistrationandbuy():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registrationandbuy(self):
    self.driver.get("https://magento.softwaretestingboard.com/")
    self.driver.find_element(By.LINK_TEXT, "Create an Account").click()
    self.driver.find_element(By.ID, "firstname").click()
    self.driver.find_element(By.ID, "firstname").send_keys("Rei")
    self.driver.find_element(By.ID, "lastname").click()
    self.driver.find_element(By.ID, "lastname").send_keys("S")
    self.driver.find_element(By.ID, "email_address").click()
    self.driver.find_element(By.ID, "email_address").send_keys("rei1445@hotmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Rei12345")
    self.driver.find_element(By.ID, "password-confirmation").click()
    self.driver.find_element(By.ID, "password-confirmation").send_keys("Rei12345")
    self.driver.find_element(By.CSS_SELECTOR, ".submit > span").click()
    self.driver.find_element(By.ID, "ui-id-5").click()
    self.driver.find_element(By.LINK_TEXT, "Tops").click()
    self.driver.find_element(By.LINK_TEXT, "Cassius Sparring Tank").click()
    self.driver.find_element(By.ID, "option-label-size-143-item-168").click()
    self.driver.find_element(By.ID, "option-label-color-93-item-50").click()
    self.driver.execute_script("window.scrollTo(0,364.79998779296875)")
    self.driver.find_element(By.CSS_SELECTOR, "#product-addtocart-button > span").click()
    self.driver.execute_script("window.scrollTo(0,417.6000061035156)")
    self.driver.find_element(By.LINK_TEXT, "shopping cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkout > span").click()
    self.driver.find_element(By.ID, "V6YE3GY").click()
    self.driver.find_element(By.ID, "LDKY5JR").send_keys("rrr")
    self.driver.find_element(By.ID, "XC8I9SG").click()
    self.driver.find_element(By.ID, "XC8I9SG").send_keys("fakir road")
    self.driver.find_element(By.ID, "F78LB3I").click()
    self.driver.find_element(By.ID, "F78LB3I").send_keys("Dhaka")
    self.driver.find_element(By.ID, "T8SF0NY").click()
    self.driver.find_element(By.ID, "WHKE627").click()
    dropdown = self.driver.find_element(By.ID, "WHKE627")
    dropdown.find_element(By.XPATH, "//option[. = 'Bangladesh']").click()
    self.driver.find_element(By.ID, "T8SF0NY").click()
    self.driver.find_element(By.ID, "T8SF0NY").send_keys("1205")
    self.driver.find_element(By.ID, "VGAULX5").click()
    self.driver.find_element(By.ID, "VGAULX5").send_keys("Dhaka")
    self.driver.find_element(By.ID, "DL3I4YX").click()
    self.driver.find_element(By.ID, "DL3I4YX").send_keys("0198888888")
    self.driver.find_element(By.NAME, "ko_unique_5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".button > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".checkout > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header:nth-child(2) > .customer-welcome .action").click()
    self.driver.find_element(By.LINK_TEXT, "Sign Out").click()
  
